apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiod
spec:
  profile: default
  tag: 1.15.4
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  components:
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu:    100m  
            memory: 200Mi  
          limits:
            cpu:    1000m  
            memory: 2048Mi  
        hpaSpec:
          maxReplicas: 3  
          minReplicas: 3  
    ingressGateways:
      - name: istio-ingressgateway          # istio-gw
        enabled: true   
        k8s:
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu:    2000m  
              memory: 1024Mi  
          hpaSpec:
            maxReplicas: 3  
            minReplicas: 3              
